<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lesson-20 with Biruk</title>
    <link rel="stylesheet" href="/lesson-16/lesson16.css">
    <script src="lesson20.js"></script>
    <img id="norImg" src="/JavaScript-logo.png" alt="">
</head>
<body>
    <h1 id="speH1"><span id="spePara">ERRORS</span> AND <span id="spePara">EXCEPTIONS</span> Part-2</h1>
    <h2 id="spePara">A few more details about JavaScript errors and exceptions</h2>
    <p>
        Let's try to organize the information about errors and exceptions, and above all, their handling. This time, let's look at the problem from a strictly functional point of view. 
        We will start with an overview of the most important types of errors detected by JavaScript, discuss in more detail the try... catch construction, and show that we can also 
        directly throw exceptions.

    </p>
    <h2 id="spePara">Basic types of errors</h2>
    <p>
        There are a few underlying types of errors that JavaScript produces. Most often, especially at the beginning, you will encounter syntax and reference errors. 
        We will also discuss type and range errors.
        <h2 id="speH1"><span id="spePara">SyntaxError</span></h2>
        <p>
            As we previously said, a <b id="spePara">SyntaxError</b> appears when a code is ill-formed, when there are typos in the keywords, unmatching parentheses or brackets, etc. 
            The code can’t even be executed, as JavaScript isn’t able to understand it. The corresponding error is therefore thrown before the program is started.
            <pre>
                <code>
                    "use strict";
                    iff (true) { //-> Uncaught SyntaxError: Unexpected token '{'
                        console.log("true");
                    }
                </code>
            </pre>
            <p>
                In the example above, we’ve made a typo in the keyword <b id="spePara">if</b>, adding an additional letter f. 
                The JavaScript engine treats the unknown name as a function call (it finds the round brackets after iff) and 
                is surprised by the presence of a curly bracket.
            </p>
        </p>

        <h2 id="speH1"><span id="spePara">ReferenceError</span></h2>
        <p>
            We’ve seen this one already. It occurs when we try to access a function or a variable that doesn't exist. The JavaScript engine does not know the meaning of the given name, 
            so it is an error that we will classify as a semantic error. The corresponding exception is thrown at the execution time of the program, when the wrong instruction is reached 
            (i.e. in JavaScript, semantic errors are run-time errors).
            <pre>
                <code>
                    let a = b; // -> Uncaught ReferenceError: b is not defined
                </code>
            </pre>
            <p>
                The attempt to declare variable a is unsuccessful because at the same time, we want to initialize it with the value of variable b. Variable b has not been declared anywhere before, 
                so the JavaScript engine does not know this name.
                <pre>
                    <code>
                        fun(); // -> Uncaught ReferenceError: fun is not defined
                    </code>
                </pre>
            </p>
            <p>
                This time, we’ve tried to call the function fun. If we haven’t declared it before, and there is no function with this name among the standard JavaScript functions, the call ends in an error.
            </p>
        </p>

        <h2 id="speH1"><span id="spePara">TypeError</span></h2>
        <p>
            This type of error occurs when a certain value is not of the expected type (i.e. you try to perform an operation on it that is not acceptable). Typical examples are changing the constant value 
            or checking the length of a variable that is not a string. This error is particularly important when working with objects that are outside the scope of this course 
            (we will talk about them in the next part of the course). This is a typical <b id="spePara">run-time error</b>, so the appropriate exception will be thrown while the program is running, 
            after reaching the problematic instruction.
            <pre>
                <code>
                    const someConstValue = 5;
                    someConstValue = 7; // -> Uncaught TypeError: Assignment to constant variable.
                </code>
            </pre>
            <p>
                Trying to store the new value to the constant someConstValue has failed for obvious reasons, resulting in a TypeError.
                <pre>
                    <code>
                        let someNumber = 10;
                        someNumber.length(); // -> Uncaught TypeError: someNumber.length is not a function
                    </code>
                </pre>
            </p>
            <p>
                This time, we’ve tried to treat the contents of the variable <b id="spePara">someNumber</b> as a string, and check its length. 
                The JavaScript engine notices that the variable stores a number, and such an operation is not allowed.
            </p>
        </p>

        <h2 id="speH1"><span id="spePara">RangeError</span></h2>
        <p>
            This type of error is generated when you pass a value to a function that is outside its acceptable range.
            <br><br>
            Again, it is a <b id="noticed">run-time error</b>, and the exception is thrown while the program is running, after reaching the wrong instruction. In fact, this exception is more useful when writing your own 
            functions and handling errors. You can then throw an exception in certain situations.
            <pre>
                <code>
                    let testArray1 = Array(10);
                    console.log(testArray1.length); // -> 10
                    let testArray2 = Array(-1); // -> Uncaught RangeError: Invalid array length
                    console.log(testArray2.length);

                </code>
            </pre>
            <p>
                In the example, we’ve attempted to create two arrays, using the constructor (i.e. de facto function) <b id="spePara">Array</b>. If we pass one argument to this function, it will be treated as the size of the newly created array. 
                The first array (<b id="spePara">testArray1</b>) is created without any problem. As you can guess, creating a <b id="spePara">testArray2</b> array with a negative length fails.
            </p>
        </p>

        <h2 id="speH1"><span id="spePara">OTHER ERRORS</span></h2>
        <p>
            There are a few more error types: <b id="spePara">EvalError</b>, <b id="spePara">InternalError</b>, and <b id="spePara">URIError</b>, but they’re rather rare, and we’ll come back to them if needed.
        </p>

        <h2 id="speH1">THE <span id="spePara">try ... catch</span> STATEMENTS</h2>
        <p>
            As we said before, exceptions interrupt the program execution. The <b id="spePara">try...catch</b> construction, which we also mentioned before, allows you to change this default action. The program will interrupt 
            what it is currently doing, but it will not terminate automatically. The syntax for <b id="spePara">try...catch</b> looks like this:
            <pre>
                <code>
                    try {
                        // code to try
                    } catch (error) {
                        // code to run in case of an error, which throw an exception
                    }                    
                </code>
            </pre>
            <p>
                The basic premise is simple: if we have a piece of code that can possibly go wrong, we can enclose it in the <b id="spePara">try</b> clause. JavaScript will try to execute this code, and if any error occurs and an exception is thrown, 
                the code inside the <b id="spePara">catch</b> block will be executed; if the <b id="spePara">try</b> code is executed without errors, then the <b id="spePara">catch</b> block is ignored. After executing the commands from the <b id="spePara">catch</b> block, 
                the program will continue to run from the first instruction outside the <b id="spePara">try...catch</b> statement.
                <br><br>
                Note that the <b id="spePara">catch</b> keyword is followed by parentheses containing the parameter error. This is a variable name that will hold information about the error that was caught, and it can have any valid name, 
                but the names <b id="spePara">error</b>, <b id="spePara">err</b>, or just <b id="spePara">e</b>, are commonly used. In the case of an exception thrown by JavaScript, the error object will contain information about 
                the error type, and is converted to a string to be logged or processed in any way the developer needs.
                <pre>
                    <code>
                        try {
                            let a = b;
                        } catch (error) {
                            console.log("Caught " + error); // -> Caught ReferenceError: b is not defined
                        }
                        console.log("We handled the exception!"); // -> we handled the exception!                        
                    </code>
                </pre>
            </p>
        </p>
    </p>
    
</body>
</html>